import AppKit
import RelayCore

/// Raycast lists a local catalog and submits a one-use request file before opening the URL.
/// A URL alone cannot trigger a capture or send; prompts and destinations always come from saved settings.
@MainActor final class RelayApplicationDelegate: NSObject, NSApplicationDelegate {
    static weak var raycastBridge: RaycastBridge?

    func application(_ application: NSApplication, open urls: [URL]) {
        for url in urls { Self.raycastBridge?.open(url) }
    }
}

@MainActor final class RaycastBridge {
    struct Entry: Codable {
        let id: UUID
        let name: String
        let readReplies: Bool
        let hotkey: String?
        let confirmBeforeSending: Bool
    }
    struct Catalog: Codable {
        let version: Int
        let applicationPath: String
        let useCases: [Entry]
    }
    struct Request: Codable {
        let useCaseID: UUID
        let createdAt: Double
        let expectedBundleID: String
    }
    struct Response: Codable {
        let accepted: Bool
        let message: String
    }
    private var onRun: ((Request) throws -> Void)?
    let directory: URL

    init(directory: URL = PrivateStorage.directory) { self.directory = directory }

    func start(onRun: @escaping (Request) throws -> Void) {
        self.onRun = onRun
        // SwiftUI installs its event handlers after AppModel.init. Use the lifecycle delegate
        // instead of an Apple Event handler that SwiftUI can replace during launch.
        RelayApplicationDelegate.raycastBridge = self
    }

    func publish(_ settings: Settings) throws {
        let catalog = Catalog(version: 1, applicationPath: Bundle.main.bundleURL.path, useCases: settings.screenUseCases.filter(\.enabled).map {
            Entry(id: $0.id, name: $0.name, readReplies: $0.readReplies, hotkey: $0.hotkey?.title,
                  confirmBeforeSending: $0.confirmBeforeSending)
        })
        try PrivateFiles.write(JSONEncoder().encode(catalog), to: directory.appendingPathComponent("screen-use-cases.json"))
        try publishCommands(catalog)
    }

    var scriptsDirectory: URL { directory.appendingPathComponent("raycast-scripts") }

    func publishCommands(_ catalog: Catalog) throws {
        try PrivateFiles.prepareDirectory(scriptsDirectory)
        var filenames = Set<String>()
        for entry in catalog.useCases {
            let filename = "talk-\(entry.id.uuidString).sh"
            filenames.insert(filename)
            let url = scriptsDirectory.appendingPathComponent(filename)
            let data = Data(Self.command(entry, applicationPath: catalog.applicationPath).utf8)
            if (try? PrivateFiles.read(url)) != data { try PrivateFiles.write(data, to: url) }
            try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: url.path)
        }
        for url in try FileManager.default.contentsOfDirectory(at: scriptsDirectory, includingPropertiesForKeys: nil) {
            let name = url.lastPathComponent
            guard name.hasPrefix("talk-"), name.hasSuffix(".sh"),
                  UUID(uuidString: String(name.dropFirst(5).dropLast(3))) != nil,
                  !filenames.contains(name) else { continue }
            try FileManager.default.removeItem(at: url)
        }
    }

    static func command(_ entry: Entry, applicationPath: String) -> String {
        // Titles are comments, never shell code. Flatten control characters and Unicode line breaks.
        let title = entry.name.components(separatedBy: .newlines.union(.controlCharacters)).joined(separator: " ")
        let executable = applicationPath + "/Contents/MacOS/LocalVoiceRelay"
        let quoted = "'" + executable.replacingOccurrences(of: "'", with: "'\"'\"'") + "'"
        return """
        #!/bin/sh
        # @raycast.schemaVersion 1
        # @raycast.title talk \(title)
        # @raycast.mode silent
        # @raycast.packageName Talk to Webex bot
        # @raycast.icon 🗣️
        # Generated by Talk to Webex bot. Edit use cases in the app.
        exec \(quoted) --run-screen-use-case '\(entry.id.uuidString)'

        """
    }

    static func requestID(from url: URL) -> UUID? {
        guard let parts = URLComponents(url: url, resolvingAgainstBaseURL: false),
              parts.scheme == "talk-to-webex-bot", parts.host == "run", parts.path.isEmpty,
              parts.user == nil, parts.password == nil, parts.port == nil, parts.fragment == nil,
              let items = parts.queryItems, items.count == 1, items[0].name == "request",
              let value = items[0].value else { return nil }
        return UUID(uuidString: value)
    }

    func consume(_ id: UUID, now: Date = Date()) throws -> Request {
        let url = directory.appendingPathComponent("raycast-requests/\(id.uuidString).json")
        let data = try PrivateFiles.read(url, maximumBytes: 4096)
        // Consume before validation/execution so a replay cannot repeat a Webex send.
        try FileManager.default.removeItem(at: url)
        let request = try JSONDecoder().decode(Request.self, from: data)
        let age = now.timeIntervalSince1970 - request.createdAt
        guard age.isFinite, (0...30).contains(age), !request.expectedBundleID.isEmpty,
              !["com.raycast.macos", "org.localvoicerelay.app", "com.apple.loginwindow"].contains(request.expectedBundleID) else {
            throw RelayError.message(L10n.text("Raycastの実行要求が無効か期限切れです。対象ウィンドウから選び直してください。"))
        }
        return request
    }

    func open(_ url: URL) {
        guard let id = Self.requestID(from: url) else { return }
        let response: Response
        do {
            let request = try consume(id)
            guard let onRun else { return }
            try onRun(request)
            response = Response(accepted: true, message: L10n.text("実行を開始しました。"))
        } catch {
            response = Response(accepted: false, message: error.localizedDescription)
        }
        let result = directory.appendingPathComponent("raycast-requests/\(id.uuidString).response.json")
        if let data = try? JSONEncoder().encode(response) { try? PrivateFiles.write(data, to: result) }
    }
}
