// English translations keyed by Japanese source text. {0}, {1}, … are interpolation arguments.
import Foundation

extension L10n {
    static let english: [String: String] = [
        "停止": "Stop",
        "待受": "Listening",
        "録音": "Recording",
        "認識中": "Recognizing",
        "送信準備": "Preparing to send",
        "送信前確認": "Confirm before sending",
        "送信": "Sending",
        "返信待ち": "Waiting for a reply",
        "読み上げ": "Speech output",
        "エラー": "Error",
        "設定を保存して待受を開始してください。": "Save your settings and start listening.",
        "未確認": "Not checked",
        "最近のDMを最大5件表示します。": "Shows up to 5 recent DMs.",
        "返信監視はまだ実行していません。": "Reply monitoring has not started yet.",
        "音声待機: 未開始": "Voice standby: Not started",
        "マイク未開始": "Microphone not started",
        "接続確認です。短く返答してください。": "This is a connection test. Please reply briefly.",
        "ウェブエックスの接続を確認しました。\nエーピーアイの確認間隔はひゃくミリ秒です。\n会議はじゅうさんじから始まります。\n今日の予定を順番に説明します。\n午前中は資料を確認してください。\n午後は必要な情報を整理します。\n進み具合は五十パーセントです。\n音量はプラスボタンで調整できます。\nこれで最後の文です。": "The Webex connection has been confirmed.\nThe API polling interval is one hundred milliseconds.\nThe meeting starts at one p.m.\nLet me go through today's schedule.\nPlease review the documents this morning.\nOrganize the information this afternoon.\nProgress is at fifty percent.\nUse the plus button to adjust the volume.\nThis is the last sentence.",
        "未保存の変更を取り消しました。": "Unsaved changes were discarded.",
        "設定をこのMacに保存しました。": "Settings saved on this Mac.",
        "必要な権限を確認しました。操作を開始できます。": "Required permissions are ready. You can start.",
        " 送信中だったため成否はWebexのDMで確認してください。自動再送しません。": " A send was in progress. Check the Webex DM to confirm the result. It will not be resent automatically.",
        "ローカル音声環境とWebex認証を確認しています。": "Checking the local speech environment and Webex authentication.",
        "本人照合用の参照音声を録音または選択してください。": "Record or select reference audio for speaker verification.",
        "マイク入力あり: %.1f dB / 検出しきい値 %.1f dB": "Microphone input: %.1f dB / Detection threshold: %.1f dB",
        "許可済みのマイク入力を開始しています。": "Starting microphone input with the existing permission.",
        "入力デバイス: {0} — 音声フレーム待ち": "Input device: {0} — Waiting for audio frames",
        "合言葉を待っています。停止ボタンでマイクを解放します。": "Waiting for a wake phrase. Press Stop to release the microphone.",
        "マイク入力を再接続できませんでした。macOSと会議アプリの入力デバイスを確認し、マイクテストを実行してください。": "Could not reconnect the microphone. Check input devices in macOS and your meeting app, then run the microphone test.",
        "マイクの変更を検出しました。入力を再接続しています。": "Microphone change detected. Reconnecting the input.",
        "マイクを再接続しました。合言葉からもう一度話してください。": "Microphone reconnected. Start again with the wake phrase.",
        "長い音声区間を破棄しました。常時待受は継続しています。一呼吸置き、合言葉から話してください。": "Discarded a long audio segment. Listening continues. Pause briefly, then start with the wake phrase.",
        "認識待ちの音声を破棄しました。常時待受は継続しています。合言葉から話してください。": "Discarded queued audio. Listening continues. Start again with the wake phrase.",
        "音声を認識できませんでした。": "Could not recognize the audio.",
        "発話を検出できませんでした。": "No speech was detected.",
        "合言葉を待っています。": "Waiting for a wake phrase.",
        "合言葉を検出しました。続けて指示を話してください。指示の音声で本人照合します。": "Wake phrase detected. Continue with your command. Your command audio will be used for speaker verification.",
        "合言葉を受け付けました。続けて指示を話してください。短い指示も受け付けます。": "Wake phrase accepted. Continue with your command. Short commands are also accepted.",
        "返信用の合言葉を受け付けました。スレッドに返す内容を話してください。": "Reply wake phrase accepted. Say what you want to send to the thread.",
        "指示の受付を区切り、次の合言葉を待っています。常時待受は継続しています。": "Command time expired. Waiting for the next wake phrase. Listening continues.",
        "送信前に指示の音声で本人照合しています。": "Verifying the speaker using the command audio before sending.",
        "本人照合を確認できませんでした。": "Could not verify the speaker.",
        "送信内容を準備しています。": "Preparing the message.",
        "返信先がありません。このアプリで相手の返信を受け取ってから、返信用の合言葉を話してください。": "No reply target is available. Receive a reply in this app before using the reply wake phrase.",
        "本文・画像・宛先を確認してください。": "Check the message, image, and destination.",
        "送信を取り消しました。": "Sending was canceled.",
        "送信後に返信を監視します。": "Replies will be monitored after sending.",
        "返信の読み上げはOFFです。監視しません。": "Read replies is off. Replies will not be monitored.",
        "Webexへ送信しています。": "Sending to Webex.",
        "送信しました。": "Message sent.",
        "送信は完了しましたが、返信を照合する送信時刻がありません。Webexで確認してください。": "The message was sent, but its timestamp is unavailable for matching replies. Check Webex.",
        "ソナー音を再生できません。返信監視は続けます。": "Could not play the sonar sound. Reply monitoring continues.",
        "音声待機: Mac標準音声": "Voice standby: Mac system voice",
        "音声待機: 返信後に準備": "Voice standby: Prepare after reply",
        "音声待機: モデルと参照音声を準備中": "Voice standby: Preparing model and reference audio",
        "音声待機: 準備完了": "Voice standby: Ready",
        "音声待機: 準備できませんでした": "Voice standby: Preparation failed",
        "返信の新着と本文更新を確認しています。": "Checking for new replies and message updates.",
        "取得 {0}回 / 返信候補 {1}件 / 途中表示 {2}件 / 同一IDの本文更新 {3}回": "Polls: {0} / Reply candidates: {1} / In-progress messages: {2} / Same-ID updates: {3}",
        "同じDMに別の送信がありました。返信の取り違えを避けるため読み上げ監視を終了しました。": "Another message was sent in the same DM. Reply monitoring stopped to avoid reading the wrong reply.",
        "返信を確認しました。最初の音声を準備しています。": "Reply received. Preparing the first audio segment.",
        "返信をローカル音声で読み上げています。": "Reading the reply using local speech output.",
        " / 返信確定から再生開始 %.1f秒": " / Reply finalized to playback: %.1f s",
        " / 読み上げ完了": " / Speech completed",
        "API制限の解除を待っています。送信の再実行は行いません。": "Waiting for the API rate limit to clear. The message will not be resent.",
        "接続を再確認しています（返信の取得のみ）。": "Rechecking the connection (reply retrieval only).",
        " / 返信待ち終了（送信済み・再送なし・待受へ復帰）": " / Reply wait ended (sent, no resend, listening resumed)",
        "操作が完了しました。": "Operation completed.",
        "音声待機: 停止（モデルを解放）": "Voice standby: Stopped (model released)",
        "送信中に停止しました。成否はWebexのDMで確認してください。自動再送しません。": "Stopped during sending. Check the Webex DM to confirm the result. It will not be resent automatically.",
        "停止しました。マイクを解放しています。": "Stopped. Releasing the microphone.",
        "ローカル環境を確認しました。": "Local environment checked.",
        "試聴する文章は1〜20,000文字で入力してください。": "Enter between 1 and 20,000 characters for the speech preview.",
        "読み上げが終わりました。発音と声質を確認してください。": "Speech finished. Check the pronunciation and voice quality.",
        "許可済みのマイクをテストします。Webexへは送信しません。": "Testing the microphone with the existing permission. Nothing will be sent to Webex.",
        "テスト中にマイクの音声形式が変わりました。入力デバイスが安定してから、もう一度テストしてください。": "The microphone audio format changed during the test. Wait for the input device to stabilize, then try again.",
        "5秒間のテスト録音中です。合言葉と短い指示を話してください。送信はしません。": "Recording a 5-second test. Say the wake phrase and a short command. Nothing will be sent.",
        "マイクから音声フレームが届きませんでした。macOSのサウンド設定と会議アプリの入力デバイスを確認し、待受を停止してから再テストしてください。": "No audio frames arrived from the microphone. Check input devices in macOS Sound settings and your meeting app. Stop listening, then test again.",
        "音声フレームは届いていますが、入力音量がゼロです。macOSのサウンド設定で内蔵マイクの入力音量を確認してください。": "Audio frames are arriving, but the input volume is zero. Check the built-in microphone input volume in macOS Sound settings.",
        "5秒録音の入力レベル最大: %.0f%%（待受と同じ録音経路）": "Peak input level during the 5-second recording: %.0f%% (same recording path as listening)",
        "認識できませんでした。入力デバイスと音量を確認してください。": "Recognition failed. Check the input device and volume.",
        "マイク・文字起こし・合言葉の一致を確認しました。送信していません。": "Microphone, transcription, and wake phrase match confirmed. Nothing was sent.",
        "文字起こしは成功しましたが、合言葉が一致しません。表示された表記を別候補として登録できます。": "Transcription succeeded, but the wake phrase did not match. You can register the displayed spelling as another candidate.",
        "指示を受け付けています": "Accepting your command",
        "合言葉を待っています": "Waiting for a wake phrase",
        "発行時刻不明。保存時刻から期限を推測せず、5分ごとにAPIで確認します。": "Issue time is unknown. The API checks validity every 5 minutes; the save time is not used to estimate expiry.",
        "入力された発行時刻では有効期間内です。APIで別途確認します。": "Within the validity period based on the entered issue time. Also checked through the API.",
        "入力された発行時刻から、期限まで30分以内です。更新してください。": "Less than 30 minutes remain based on the entered issue time. Renew the token.",
        "入力された発行時刻から12時間を過ぎています。更新してください。": "More than 12 hours have passed since the entered issue time. Renew the token.",
        "参照音声をこのMacのアプリ用フォルダへコピーしました。他の設定は「変更を保存」で適用します。": "Reference audio copied to this Mac's app folder. Apply other settings with Save Changes.",
        "許可済みのマイクで参照音声を録音します。": "Recording reference audio with the existing microphone permission.",
        "参照音声の録音を開始できません。": "Could not start recording reference audio.",
        "参照音声を録音中です。10〜20秒話し、録音終了を押してください（最大30秒）。": "Recording reference audio. Speak for 10–20 seconds, then press Finish Recording (maximum 30 seconds).",
        "録音が3秒未満です。10〜20秒の参照音声を録り直してください。": "The recording is shorter than 3 seconds. Record 10–20 seconds of reference audio again.",
        "参照音声を保存しました。これは追加学習ではありません。声の再現用には読んだ本文も入力してください。": "Reference audio saved. This does not train the model. For voice cloning, also enter the text you read.",
        "認証が無効です。新しいAPI Keyを入力してください。": "Authentication is invalid. Enter a new API key.",
        "Webexの認証を更新しました。待受を開始できます。": "Webex authentication renewed. You can start listening.",
        "有効（{0}に確認）": "Valid (checked at {0})",
        "設定のWebex欄でトークンをキーチェーンに保存してください。": "Save your token in Keychain from the Webex settings.",
        "保存済みトークンがありません。アプリ内で入力して保存してください。": "No saved token found. Enter and save one in the app.",
        "保存済みトークンを読み込みました。Webexで有効性を確認します。": "Saved token loaded. Checking its validity with Webex.",
        "認証を確認しました。送信先DMを選んでください。": "Authentication confirmed. Select a destination DM.",
        "DM検索を停止しました。更新ボタンで再開できます。": "DM search stopped. Use Refresh to resume.",
        "最近のやりとり順に、一致するDMを最大5件探しています。": "Searching for up to 5 matching DMs, ordered by recent activity.",
        "条件に一致するDMはありません。": "No matching DMs found.",
        "{0}件 • 最近のやりとり順 • 最大5件": "{0} results • Recent activity first • Up to 5",
        "送信先DMを選んでください。": "Select a destination DM.",
        "マイクの音声形式に対応できません。": "The microphone audio format is not supported.",
        "マイク音声の変換に失敗しました。入力デバイスを確認し、Macの追加音声処理を無効にして再開してください。": "Could not convert microphone audio. Check the input device, turn off Mac audio processing, then restart.",
        "録音が空です。": "The recording is empty.",
        "録音バッファを作成できません。": "Could not create a recording buffer.",
        "参照音声は3〜30秒の音声ファイルを選んでください。": "Select an audio file between 3 and 30 seconds long as the reference.",
        "参照音声をWAVに変換できません。": "Could not convert the reference audio to WAV.",
        "情報": "Info",
        "注意": "Warning",
        "アプリ": "App",
        "音声入力": "Voice Input",
        "権限": "Permissions",
        "アプリを起動しました": "App launched",
        "設定を保存しました": "Settings saved",
        "停止してマイクと音声モデルを解放しました": "Stopped and released the microphone and speech model",
        "マイク入力を開始しました": "Microphone input started",
        "送信しないマイクテストを完了しました": "Microphone test completed without sending",
        "マイクテストの録音を終了しました": "Microphone test recording ended",
        "音声を認識しました": "Speech recognized",
        "認識の信頼度または音声区間が不足しています": "Insufficient recognition confidence or speech duration",
        "合言葉を検出しました": "Wake phrase detected",
        "話者類似度を計測しました": "Speaker similarity measured",
        "前面ウィンドウの画像とOCRを取得しました": "Captured the front window image and OCR",
        "対象画面を取得できないため、画像とOCRを省いて音声の指示だけで続行します": "Could not capture the window; continuing with the voice command and omitting the image and OCR",
        "必要な権限を確認しました": "Required permissions checked",
        "ローカル音声環境の診断が完了しました": "Local speech environment diagnostics completed",
        "Webex認証は有効です": "Webex authentication is valid",
        "Webex認証が無効です。更新を案内しました": "Webex authentication is invalid; renewal guidance shown",
        "保存済みトークンを読み込めませんでした。Webex設定を確認してください": "Could not load the saved token; check Webex settings",
        "新しいトークンを検証し、キーチェーンに保存しました": "New token validated and saved in Keychain",
        "既定のブラウザでトークン取得ページを開きました": "Token page opened in the default browser",
        "取得ページを開けませんでした。認証画面から再度開いてください": "Could not open the token page; try again from the authentication screen",
        "最近のDMを取得しました": "Recent DMs retrieved",
        "Webexへの送信処理を開始しました": "Started sending to Webex",
        "Webexへの送信が完了しました": "Sent to Webex",
        "送信結果が不明です。再送せずWebexで確認してください": "Send result unknown; check Webex before resending",
        "返信の新着と同一IDの更新を確認しました": "Checked new replies and same-ID updates",
        "返信待ちを終了し、次の合言葉の待受へ戻ります。送信は繰り返しません": "Reply wait ended; returning to the next wake phrase without resending",
        "25秒に達した音声区間を破棄しました。常時待受は継続します": "Discarded an audio segment at 25 seconds; listening continues",
        "処理が追いつかない音声を破棄しました。常時待受は継続します": "Discarded audio that could not be processed in time; listening continues",
        "指示の受付を区切りました。次の合言葉を待ちます": "Command window closed; waiting for the next wake phrase",
        "API制限の解除を待ちます": "Waiting for the API rate limit to clear",
        "通信に失敗しました": "Connection failed",
        "音声モデルと参照音声を準備しています": "Preparing the speech model and reference audio",
        "音声モデルの準備が完了しました": "Speech model ready",
        "読み上げの再生を開始しました": "Speech playback started",
        "読み上げが完了しました": "Speech completed",
        "未再生の長い音声区間をさらに分割して生成しました": "Subdivided and generated a long audio segment before playback",
        "次の行の音声を生成して再生待ちに追加しました": "Generated the next line and queued it for playback",
        "先行音声が尽きたため次の行の生成を待ちました": "Buffered audio ran out; waited for the next line to generate",
        "ソナー音を再生できませんでした": "Could not play the sonar sound",
        "処理に失敗しました。ホームの案内を確認してください": "Operation failed; check the guidance on Home",
        "入力デバイスの変更または音声フレームの途絶を検出しました": "Detected an input device change or missing audio frames",
        "マイクを再接続しました。途中の発話は破棄しました": "Microphone reconnected; incomplete speech discarded",
        "マイクの再接続が続けて失敗しました。入力デバイスを確認してください": "Microphone reconnection failed repeatedly; check the input device",
        "秒": "s",
        "件数": "Count",
        "取得回数": "Polls",
        "返信候補": "Reply candidates",
        "途中表示": "In-progress messages",
        "本文更新": "Message updates",
        "話者類似度": "Speaker similarity",
        "発話全体": "Entire utterance",
        "しきい値": "Threshold",
        "区間": "Segment",
        "入力最大": "Peak input",
        "通信エラー番号": "Network error code",
        "入力Hz": "Input Hz",
        "入力チャンネル数": "Input channels",
        "キーチェーン状態": "Keychain status",
        "マイク許可": "Microphone permission",
        "画面収録許可": "Screen recording permission",
        "スクショ有効": "Screenshot enabled",
        "行": "Line",
        "総行数": "Total lines",
        "生成秒": "Generation seconds",
        "音声秒": "Audio seconds",
        "再生残秒": "Buffered seconds",
        "開発版": "Development",
        "オン": "On",
        "オフ": "Off",
        "カスタム": "Custom",
        "Qwen（ローカル・{0}）": "Qwen (local, {0})",
        "Mac標準": "Mac system voice",
        "未選択": "Not selected",
        "## 起きたこと\n（期待した動作と、実際に起きたことを記入）\n\n## 再現手順・頻度\n1.\n2.\n頻度：\n\n## 環境\n- アプリ: {0}（ビルド {1}）\n- macOS: {2}.{3}.{4} / {5}\n- 状態: {6}\n- マイク許可: {7}\n- 画面収録許可: {8}\n- スクショ・OCR: {9} / 送信前確認: {10}\n- 返信読み上げ: {11} / 音声方式: {12}\n- 話者判定: {13}\n\n## 試した対処\n（実施したものだけ記入）\n\n## 診断イベント（直近30件、古い順）\n```text\n{14}\n```": "## What happened\n(Describe the expected and actual behavior.)\n\n## Steps to reproduce and frequency\n1.\n2.\nFrequency:\n\n## Environment\n- App: {0} (build {1})\n- macOS: {2}.{3}.{4} / {5}\n- State: {6}\n- Microphone permission: {7}\n- Screen recording permission: {8}\n- Screenshot / OCR: {9} / Confirm before sending: {10}\n- Read replies: {11} / Speech engine: {12}\n- Speaker matching: {13}\n\n## Troubleshooting attempted\n(Only list actions you have tried.)\n\n## Diagnostic events (last 30, oldest first)\n```text\n{14}\n```",
        "設定…": "Settings…",
        "すべて停止": "Stop All",
        "不具合を報告…": "Report an Issue…",
        "アプリを表示": "Show App",
        "保存して待受を開始": "Save and Start Listening",
        "待受を開始": "Start Listening",
        "終了": "Quit",
        "指示を受付中": "Accepting a command",
        "Webexへ送信済み": "Sent to Webex",
        "待機中": "Idle",
        "ローカル音声処理を起動できません。": "Could not start local speech processing.",
        "音声処理が終了しました。処理時間・メモリ・モデル配置を確認してください。": "Speech processing exited. Check processing time, memory, and model files.",
        "Python環境がありません。scripts/setup-runtime.sh を実行してください。": "Python environment not found. Run scripts/setup-runtime.sh.",
        "音声処理がバンドルされていません。scripts/build.sh で.appをビルドしてください。": "Speech processing is missing from the bundle. Build the app with scripts/build.sh.",
        "許可済み": "Allowed",
        "未設定": "Not configured",
        "未許可": "Not allowed",
        "制限あり": "Restricted",
        "マイク": "Microphone",
        "画面収録": "Screen Recording",
        "保存先が通常のフォルダではありません。保存先を確認してください。": "The storage location is not a regular folder. Check the destination.",
        "保存ファイルの形式またはサイズが不正です。": "The saved file format or size is invalid.",
        "保存ファイルが上限を超えています。": "The saved file exceeds the size limit.",
        "画像をPNGに変換できません。": "Could not convert the image to PNG.",
        "{0}（プレミアム）": "{0} (Premium)",
        "{0}（拡張）": "{0} (Enhanced)",
        "日本語音声が未配置です。システム設定 → アクセシビリティ → 読み上げコンテンツで先に取得してください。": "No English voice is installed. Download one first in System Settings → Accessibility → Spoken Content / Read & Speak.",
        "読み上げが停止したか、ローカル音声を利用できません。": "Speech stopped or the local voice is unavailable.",
        "音声アシスタントの常時待受": "Keep the voice assistant listening",
        "一時ファイルを作成できません。": "Could not create a temporary file.",
        "macOSが保存済みトークンの読み込みを許可しませんでした（{0}）。確認画面が出なかった場合は、キーチェーンのロック状態とアプリの署名を確認してください。": "macOS did not allow access to the saved token ({0}). If no dialog appeared, check whether Keychain is locked and verify the app's signature.",
        "保存済みトークンを自動では読み込めませんでした（{0}）。「保存済みトークンを読み込む」でmacOSのアクセス確認を進めてください。": "Could not load the saved token automatically ({0}). Choose Load Saved Token to continue the macOS access check.",
        "キーチェーンのアクセス方法を設定できません。": "Could not configure Keychain access.",
        "キーチェーンの読み込みをキャンセルしました。自動では再試行しません。": "Keychain access was canceled. It will not be retried automatically.",
        "保存済みトークンの形式を読み取れません。アプリ内で保存し直してください。": "Could not read the saved token format. Save it again in the app.",
        "キーチェーンに保存できません（{0}）。": "Could not save to Keychain ({0}).",
        "キーチェーンを更新できません（{0}）。": "Could not update Keychain ({0}).",
        "再生用の音声を読み込めません。": "Could not load audio for playback.",
        "音声生成中に再生形式が変わりました。": "The playback format changed during speech generation.",
        "再生用のPCM形式が不正です。": "The PCM playback format is invalid.",
        "再生用メモリを確保できません。": "Could not allocate memory for playback.",
        "音声の再生が進みません。出力デバイスを確認してください。": "Audio playback is not progressing. Check the output device.",
        "ローカル音声環境と、モデルの保存先を管理します。": "Manage the local speech environment and model locations.",
        "Pythonの絶対パス": "Absolute Python path",
        "Whisperモデルの絶対パス": "Absolute Whisper model path",
        "Qwenモデルの絶対パス": "Absolute Qwen model path",
        "ローカル環境を診断": "Diagnose Local Environment",
        "取得済みのローカル環境": "Installed local environment",
        "結果はログ画面で確認できます。モデルが未配置の場合は案内を表示し、自動で取得しません。Qwenの標準は models/voice-1.7b（1.7B・8bit）です。以前の models/voice（0.6B・4bit）は省メモリ用に残せます。": "View results in Logs. Missing models are reported without downloading them. The standard Qwen model is models/voice-1.7b (1.7B, 8-bit). Keep models/voice (0.6B, 4-bit) for lower memory use.",
        "初回だけ、リポジトリで次のコマンドを実行します。": "Run these commands in the repository once during setup.",
        "scripts/setup-runtime.sh\nscripts/download-models.sh asr\n\n自分の声を再現する場合：\nscripts/setup-runtime.sh --voice\nscripts/download-models.sh voice\n\n16GBのMacなど省メモリで使う場合：\nscripts/download-models.sh voice-small": "scripts/setup-runtime.sh\nscripts/download-models.sh asr\n\nFor voice cloning:\nscripts/setup-runtime.sh --voice\nscripts/download-models.sh voice\n\nFor lower memory use, such as on a 16 GB Mac:\nscripts/download-models.sh voice-small",
        "初回セットアップ": "Initial setup",
        "依存関係とモデルの取得はセットアップ時だけ通信します。通常の音声処理はMac内で完結します。": "Dependencies and models use the network only during setup. Normal speech processing runs entirely on your Mac.",
        "設定と参照音声": "Settings and reference audio",
        "このMacのアプリ用フォルダ": "App folder on this Mac",
        "認証情報": "Credentials",
        "macOSキーチェーン": "macOS Keychain",
        "診断ログ": "Diagnostic logs",
        "このMacに直近500件": "Last 500 events on this Mac",
        "データの保存": "Data storage",
        "ログには処理の種類と診断の数値を記録します。トークン・会話本文・宛先・画像・録音は記録しません。": "Logs contain operation types and diagnostic numbers. Tokens, conversations, destinations, images, and recordings are excluded.",
        "ホーム": "Home",
        "読み上げ・返信": "Speech & Replies",
        "送信内容": "Message Content",
        "詳細設定": "Advanced",
        "ログ": "Logs",
        "開始 停止 待受 会話": "start stop listen conversation",
        "API Key パスワード キーチェーン トークン 認証 DM 宛先": "API key password keychain token authentication DM destination",
        "合言葉 マイク 話者 録音 常時 ロック スリープ": "wake phrase microphone speaker recording always lock sleep language English Japanese",
        "TTS Qwen 声 再生 ソナー ポーリング 監視 タイムアウト": "TTS Qwen voice playback sonar polling monitoring timeout",
        "スクショ 画像 OCR プロンプト テンプレート スレッド 確認": "screenshot image OCR prompt template thread confirmation",
        "許可 画面収録 マイク": "permission screen recording microphone",
        "Python モデル インストール 保存先 環境": "Python model install location environment",
        "テスト エラー 診断 履歴 不具合 報告 Issue サポート": "test error diagnostics history bug report issue support",
        "送る内容と、返信の書き方を設定します。": "Configure message content and how the bot should reply.",
        "スクショ・OCRを送付": "Attach screenshot and OCR",
        "送信前に本文と画像を確認": "Review message and image before sending",
        "送信前の確認": "Before sending",
        "スクショをオンにした場合だけ前面ウィンドウを取得します。取得できない場合や画面ロック中は、画像とOCRを省いて続行します。送信前確認がオンなら、ロック解除後の確認を待ちます。オフならロック中も送信します。": "The front window is captured only when screenshots are enabled. If unavailable or the screen is locked, the image and OCR are omitted. With confirmation enabled, sending waits until you unlock and confirm. Otherwise, it can send while locked.",
        "通常の送信テンプレート": "New message template",
        "初期テンプレートに戻す": "Restore Default Template",
        "ボットへの指示": "Instructions for the bot",
        "初期値では日本語・カタカナ・短文改行で返答するよう指示します。二桁以上の数字は「じゅうさんじ」のように、意味に合ったひらがな表記を求めます。": "The default requests English replies in short sentences, one per line. Numbers and symbols should be written as natural spoken English.",
        "スレッド返信用テンプレート": "Thread reply template",
        "初期の返信テンプレートに戻す": "Restore Default Reply Template",
        "追加の返信": "Follow-up replies",
        "同じ話題へのユーザ返信として、文脈を引き継ぐよう指示します。送るのはこの指示と新しい文字起こしだけです。直前のボット回答やスクショ・OCRは付けません。": "Instructs the bot to continue the same topic using the conversation context. Only these instructions and the new transcript are sent. The previous bot reply, screenshot, and OCR are not attached.",
        "{{transcript}}：音声文字起こし\n{{ocr}}：OCR文字列\n{{#screen}}…{{/screen}}：スクショが有効なときだけ送る範囲": "{{transcript}}: Speech transcript\n{{ocr}}: OCR text\n{{#screen}}…{{/screen}}: Included only when a screenshot is available",
        "使える変数": "Available variables",
        "Webexの認証を更新してください。": "Renew your Webex authentication.",
        "API Keyを入力": "Enter API Key",
        "マイク・読み上げ・返信監視を停止": "Stop the microphone, speech output, and reply monitoring",
        "保存していない変更があります": "You have unsaved changes",
        "設定は保存済みです": "Settings are saved",
        "変更するには、上部の「停止」を押してください": "Press Stop above to change settings",
        "変更を取り消す": "Discard Changes",
        "変更を保存": "Save Changes",
        "送信内容を確認": "Review Message",
        "送信先  ·  {0}": "Destination · {0}",
        "画面を取得できないため、画像とOCRを省いて送信します。": "The screen could not be captured. The image and OCR will be omitted.",
        "スレッドへの返信": "Reply to thread",
        "返信先の確認用です。以下の引用は送信本文に含めません。": "For checking the reply target. The quoted text below is not included in the message.",
        "通常のDMメッセージ": "New DM message",
        "表示中の本文を送信します。": "The displayed message will be sent.",
        "表示中の本文と画像を送信します。": "The displayed message and image will be sent.",
        "取り消す": "Cancel",
        "Webexへ送信": "Send to Webex",
        "声で、会話を始めましょう": "Start a conversation with your voice",
        "処理中": "Processing",
        "マイク入力レベル": "Microphone input level",
        "送信先のDM": "Destination DM",
        "宛先を選択してください": "Select a destination",
        "変更": "Change",
        "スクショ・OCR": "Screenshot / OCR",
        "返信読み上げ": "Read replies",
        "会話": "Conversation",
        "表示を消去": "Clear Display",
        "この画面の会話とスレッド返信先を消去します。Webexのメッセージは残ります": "Clears this conversation and thread reply target. Messages in Webex remain.",
        "会話がここに表示されます": "Your conversation appears here",
        "待受は停止するまで続きます。\n合言葉のあとに、指示を話してください。": "Listening continues until you stop it.\nSay the wake phrase, then your command.",
        "あなた": "You",
        "Webexからの返信": "Reply from Webex",
        "返信用の合言葉で、この会話のスレッドへ返せます": "Use the reply wake phrase to reply in this conversation's thread",
        "音声処理はこのMacで完結": "Speech processing stays on this Mac",
        "テスト・ログを開く": "Open Tests & Logs",
        "次の準備": "Next setup step",
        "権限を確認": "Check Permissions",
        "保存済みトークンを読み込む": "Load Saved Token",
        "Webexを設定": "Set Up Webex",
        "DMを選ぶ": "Choose a DM",
        "音声環境を確認": "Check Speech Environment",
        "マイクと、使う機能の権限を確認してください。": "Check the microphone and permissions for the features you use.",
        "キーチェーンのアクセス確認が必要です。": "Keychain access needs confirmation.",
        "Webexの認証を確認してください。": "Check Webex authentication.",
        "声で話しかける相手のDMを選んでください。": "Select the DM you want to talk to.",
        "このMacの音声処理環境を準備してください。": "Prepare the speech processing environment on this Mac.",
        "{0}の設定を開く": "Open {0} settings",
        "合言葉と、声の受け付け方を設定します。": "Configure wake phrases and how speech is accepted.",
        "通常の合言葉": "New conversation wake phrase",
        "会話を始める": "Start a conversation",
        "例：オッケー、アシスタント。別の表記は1行ずつ登録できます。合言葉は送信文から除きます。": "Example: Okay, assistant. Register alternate spellings on separate lines. The wake phrase is removed from the message.",
        "返信用の合言葉": "Reply wake phrase",
        "スレッドへ返信する": "Reply to a thread",
        "例：オッケー、返信して。直前に受け取った返信のスレッドへ送ります。空欄にすると無効になります。通常の合言葉とは別の言葉を登録してください。": "Example: Okay, reply. Sends to the thread of the last reply received. Leave empty to disable. Use a phrase distinct from the new conversation wake phrase.",
        "登録した声を優先する": "Prefer the registered speaker",
        "声の判定方法": "Speaker matching mode",
        "登録した声を優先": "Prefer registered speaker",
        "厳格に本人照合": "Strict speaker verification",
        "類似度のしきい値": "Similarity threshold",
        "話す人の優先": "Speaker preference",
        "優先モードは短い発話も受け付けます。複数の声を区別できる場合だけ、登録した声を優先します。読み上げ用の声の再現とは別機能です。": "Preference mode accepts short utterances. It favors the registered speaker only when multiple voices can be distinguished. This is separate from voice cloning for speech output.",
        "発話を区切る無音": "Silence to end an utterance",
        "合言葉の後の受付時間": "Command window after wake phrase",
        "マイクの詳細": "Microphone details",
        "入力音量のしきい値": "Input volume threshold",
        "Macの追加音声処理": "Mac audio processing",
        "入力できないときは追加音声処理をオフにしてください。マイクテストと診断結果は「ログ」にあります。": "Turn off additional audio processing if input fails. Microphone tests and diagnostic results are in Logs.",
        "発話の区切り": "Utterance timing",
        "待受時間に上限はありません。無音は0.3〜4秒、合言葉の後の指示受付は3〜60秒です。25秒続く音声区間は破棄して待受を続けます。": "Listening has no time limit. Silence: 0.3–4 seconds. Command window: 3–60 seconds. Audio segments lasting 25 seconds are discarded while listening continues.",
        "待受中の自動スリープを防ぐ": "Prevent automatic sleep while listening",
        "常時待受": "Continuous listening",
        "画面ロック中も待受を続けます。画面の消灯とロックは妨げません。Macの蓋を閉じた場合・手動スリープ・ログアウト中は動作しません。待受中は電力を使用します。": "Listening continues while the screen is locked. Display sleep and locking still work. It stops when the lid is closed, the Mac is manually put to sleep, or you log out. Listening consumes power.",
        "今日は予定を確認します。必要な情報を整理して、順番に作業を進めます。画面に表示された内容を読み取り、分かりやすく説明してください。": "Today I will check my schedule. I will organize the information I need and work through each task in order. Please read what is on the screen and explain it clearly.",
        "参照音声の録音例": "Reference recording sample",
        "静かな場所で、普段の声で10〜20秒かけて読んでください。": "Read this in your usual voice for 10–20 seconds in a quiet place.",
        "不具合を報告": "Report an Issue",
        "症状と再現手順を追記して、下書きをコピーしてください。GitHubのフォームで内容を確認して投稿できます。": "Add the symptoms and steps to reproduce, then copy the draft. Review and submit it in the GitHub form.",
        "トークン・宛先・会話・録音は自動添付しません。追記にも個人情報を含めないでください。": "Tokens, destinations, conversations, and recordings are not attached automatically. Do not add personal information to the draft.",
        "Issue報告の下書き": "Issue report draft",
        "ブラウザを開けませんでした。下書きをコピーし、リポジトリのIssuesから報告してください。": "Could not open the browser. Copy the draft and report it from the repository's Issues page.",
        "閉じる": "Close",
        "コピー済み": "Copied",
        "下書きをコピー": "Copy Draft",
        "GitHubの報告フォームを開く": "Open GitHub Report Form",
        "フォームを開くだけでは投稿されません。": "Opening the form does not submit the report.",
        "処理の履歴": "Operation history",
        "ログの保存に失敗しました。画面内の履歴は確認できます。": "Could not save logs. The history is still available on screen.",
        "該当するログはありません": "No matching logs",
        "{0}件 · このMacに直近500件を保存": "{0} events · Last 500 saved on this Mac",
        "本文・宛先・認証情報は記録しません": "Messages, destinations, and credentials are excluded",
        "診断ログを消去しますか？": "Clear diagnostic logs?",
        "消去": "Clear",
        "このMacに保存された履歴を消去します。必要な場合は先にログをコピーしてください。": "This clears the history saved on this Mac. Copy the logs first if you need them.",
        "停止中に報告用の下書きを開きます": "Open a report draft while stopped",
        "テストを閉じる": "Close Tests",
        "診断テスト": "Diagnostic Tests",
        "診断テストを表示・非表示": "Show or hide diagnostic tests",
        "ログをコピー": "Copy Logs",
        "表示中のログをコピー": "Copy visible logs",
        "ログを消去": "Clear Logs",
        "診断ログを消去": "Clear diagnostic logs",
        "分類": "Category",
        "すべて": "All",
        "注意・エラーのみ": "Warnings and errors only",
        "ログを検索": "Search logs",
        "マイクを5秒テスト": "Test Microphone for 5 Seconds",
        "5秒間のテスト録音": "5-second test recording",
        "マイク入力": "Microphone input",
        "診断中のマイク入力レベル": "Microphone input level during diagnostics",
        "直近の認識結果（保存しません）": "Latest recognition result (not saved)",
        "接続テストで送る指示": "Command for the connection test",
        "マイクテストは送信しません。接続テストは宛先と本文を確認してから送信します。": "The microphone test sends nothing. The connection test asks you to review the destination and message before sending.",
        "声の種類と、返信を待つ間の動作を設定します。": "Configure the voice and what happens while waiting for replies.",
        "レスポンスを読み上げる": "Read replies aloud",
        "読み上げ方式": "Speech engine",
        "Mac標準音声": "Mac system voice",
        "Qwen3-TTS · 自分の声を再現": "Qwen3-TTS · Clone my voice",
        "日本語の声": "English voice",
        "自動選択": "Automatic",
        "自動選択は取得済みの最も高品質なKyokoを使います。システム設定 → アクセシビリティ → 読み上げコンテンツで「拡張」「プレミアム」の日本語音声を取得すると、ここに表示されます。": "Automatic selects the highest-quality installed English voice. Download Enhanced or Premium English voices in System Settings → Accessibility → Spoken Content / Read & Speak to list them here.",
        "参照録音で実際に読んだ全文": "Full transcript of the reference recording",
        "参照音声の背景ノイズを軽減": "Reduce background noise in reference audio",
        "声と一緒に再現される背景音を抑えます。声の響きが気になる場合は、オフの音声と比べてください。": "Reduces background sounds reproduced with your voice. Compare with this off if the voice sounds different.",
        "読み上げる声": "Voice for replies",
        "Qwenは10〜20秒の参照音声から声を再現します。参照本文は録音の全文と一致させてください。追加学習は行いません。参照音声はメモリ上で整えてから使います（低域の除去、ノイズ軽減、音量の統一。録音の長さは変えません）。返信のMarkdownや絵文字・URLは読み上げ用に言い換え、画面の表示は変えません。": "Qwen clones a voice from 10–20 seconds of reference audio. The transcript must match the full recording. No training is performed. Reference audio is prepared in memory (low-frequency filtering, noise reduction, and volume normalization, with duration preserved). Markdown, emoji, and URLs are adapted for speech; the displayed reply stays unchanged.",
        "試聴する文章": "Speech preview text",
        "この設定で読み上げを試す": "Try Speech with These Settings",
        "声を試す": "Preview voice",
        "この試聴はWebexへ送信しません。Qwenは冒頭を短く区切り、音声ができ次第読み始めます。その後は改行に沿って読み上げ、再生中も次の行を準備します。": "This preview is not sent to Webex. Qwen splits the opening into short segments and starts playback as soon as audio is ready. It then follows line breaks, preparing the next line during playback.",
        "返信待ちにソナー音を流す": "Play sonar while waiting for a reply",
        "ソナー音量": "Sonar volume",
        "返信待ちに音声モデルを準備する": "Prepare speech model while waiting",
        "約3秒ごとのソナー音が、読み上げ開始と同時に止まります。ホットスタンバイではモデルと参照音声を先に準備します。": "The sonar sounds about every 3 seconds and stops when speech begins. Hot standby prepares the model and reference audio in advance.",
        "返信の監視間隔": "Reply polling interval",
        "本文更新が止まってから待つ時間": "Wait after the last message update",
        "返信の待ち時間": "Reply timeout",
        "返信の判定条件": "Reply matching conditions",
        "送信へのスレッド返信だけを読む": "Read only threaded replies to the sent message",
        "途中表示の先頭フレーズ（1行ずつ）": "In-progress message prefixes (one per line)",
        "返信の確認": "Reply monitoring",
        "監視は100〜30,000ms、更新停止は2〜60秒、返信の待ち時間は30〜900秒。期限後は再送せず、次の合言葉の待受へ戻ります。最終回答の判定は更新停止に基づく推定です。": "Polling: 100–30,000 ms. Update settling: 2–60 seconds. Timeout: 30–900 seconds. After timeout, listening resumes without resending. Final reply detection is an estimate based on updates stopping.",
        "使い始める前に、このMacのアクセス権限を確認します。": "Check access permissions on this Mac before you start.",
        "マイクの許可を設定": "Configure Microphone Permission",
        "合言葉・指示の入力と、参照音声の録音に使います。": "Used for wake phrases, commands, and reference recordings.",
        "不要 · スクショはオフ": "Not needed · Screenshots off",
        "画面収録の許可を設定": "Configure Screen Recording Permission",
        "スクショ・OCRを使う場合に必要です。macOSの設定を変更したら、アプリを終了して開き直してください。": "Required for screenshots and OCR. After changing macOS settings, quit and reopen the app.",
        "権限を再確認": "Recheck Permissions",
        "参照音声": "Reference audio",
        "登録済み": "Registered",
        "未登録": "Not registered",
        "録音中です。普段の声で話してください。": "Recording. Speak in your usual voice.",
        "録音終了": "Finish Recording",
        "参照音声を録音": "Record Reference Audio",
        "音声ファイルを選ぶ": "Choose Audio File",
        "このMacの音声アシスタント": "Voice assistant on this Mac",
        "項目を検索": "Search settings",
        "設定項目を検索": "Search settings sections",
        "一致する項目がありません": "No matching sections",
        "設定": "Settings",
        "サポート": "Support",
        "Webexの認証を更新": "Renew Webex Authentication",
        "Webexに接続": "Connect to Webex",
        "新しいAPI Keyを入力してください。": "Enter a new API key.",
        "1. 取得ページにWebexアカウントでサインインします。": "1. Sign in to the token page with your Webex account.",
        "2. Personal Access Tokenをコピーします。": "2. Copy the Personal Access Token.",
        "3. 下の入力欄へ貼り付けて、接続を確認します。": "3. Paste it below and check the connection.",
        "取得ページをブラウザで開く": "Open Token Page in Browser",
        "ブラウザを開けませんでした。もう一度上のボタンを押してください。": "Could not open the browser. Press the button above to try again.",
        "Webex API Key（個人アクセストークン）": "Webex API Key (Personal Access Token)",
        "取得したトークンを貼り付け": "Paste your token",
        "キーチェーンに保存します。ログには記録しません。": "Saved in Keychain. Not recorded in logs.",
        "あとで": "Later",
        "保存して接続確認": "Save and Check Connection",
        "認証と、声で話しかける相手を設定します。": "Set up authentication and choose who to talk to.",
        "認証状態": "Authentication status",
        "接続済み": "Connected",
        "アクセス確認が必要": "Access confirmation needed",
        "更新が必要": "Renewal needed",
        "この操作でmacOSのアクセス確認を許可します。「有効性を確認」はパスワード画面を出しません。": "This action allows the macOS access dialog. Check Validity does not open a password dialog.",
        "API Keyを更新": "Update API Key",
        "有効性を確認": "Check Validity",
        "保存済みトークンへのアクセス": "Access to the saved token",
        "読み込みにmacOSの確認が必要な場合に使います。「常に許可」を選ぶと、同じ署名のアプリを次回も許可できます。": "Use this when macOS needs confirmation to read the token. Choosing Always Allow can permit future access by the app with the same signature.",
        "Webexアカウント": "Webex account",
        "API Key（個人アクセストークン）はキーチェーンに保存します。失効時は取得ページを既定のブラウザで開き、更新を案内します。": "The API key (Personal Access Token) is saved in Keychain. When it expires, the token page opens in your default browser with renewal guidance.",
        "選択中の宛先": "Selected destination",
        "DM名で絞り込む": "Filter by DM name",
        "DM一覧を更新": "Refresh DM List",
        "宛先を探しています…": "Finding destinations…",
        "一致する宛先がありません": "No matching destinations",
        "最近やりとりした5件を表示します。検索すると、一致する宛先の直近5件に切り替わります。\n{0}": "Shows the 5 most recent conversations. Searching shows the 5 most recent matching destinations.\n{0}",
        "トークンの発行時刻を指定する": "Specify the token issue time",
        "実際の発行時刻": "Actual issue time",
        "有効期限の目安": "Estimated expiry",
        "返信待ちのソナー音を再生できません。": "Could not play the reply waiting sonar sound.",
        "音声処理の応答が途中で終了しました。処理時間・メモリ・モデル配置を確認してください。": "The speech processing response ended early. Check processing time, memory, and model files.",
        "音声処理の出力が上限を超えました。": "Speech processing output exceeded the limit.",
        "Webex認証が切れています。設定でトークンを更新してください。": "Webex authentication has expired. Update the token in settings.",
        "Webexの呼び出し制限です。時間をおいて再実行してください。": "Webex API rate limit reached. Try again later.",
        "Webexの呼び出し制限です。約{0}秒後に再実行してください。": "Webex API rate limit reached. Try again in about {0} seconds.",
        "送信結果を確認できません。重複を避けるため自動再送しません。WebexのDMを確認してください。": "Could not confirm the send result. It will not be resent automatically to avoid duplicates. Check the Webex DM.",
        "必要な権限がありません: {0}。画面上部の「最初に権限を確認」で許可を設定し、再確認してください。画面収録を変更した場合はアプリを再起動してください。": "Required permissions are missing: {0}. Configure them in Permissions, then recheck. Restart the app after changing Screen Recording permission.",
        "オッケー、アシスタント": "Okay, assistant",
        "オッケー、返信して": "Okay, reply",
        "Working...\n考え中...\n処理中...": "Working...\nThinking...\nProcessing...",
        "読み上げの音声方式を選び直してください。": "Select the speech engine again.",
        "声の判定方法を選び直してください。": "Select the speaker matching mode again.",
        "合言葉を4文字以上で登録してください。複数候補は改行で分けます。": "Register wake phrases with at least 4 characters each. Put each candidate on a separate line.",
        "返信用の合言葉は4文字以上にして、通常の合言葉と区別できるものを登録してください。": "The reply wake phrase must have at least 4 characters and be distinct from the new conversation wake phrase.",
        "発話を区切る無音は0.3〜4秒で指定してください。": "Set the silence duration between 0.3 and 4 seconds.",
        "合言葉の後の受付時間は3〜60秒で指定してください。": "Set the command window after the wake phrase between 3 and 60 seconds.",
        "入力音量のしきい値は0.001〜0.1で指定してください。": "Set the input volume threshold between 0.001 and 0.1.",
        "類似度のしきい値は0.5〜0.99で指定してください。": "Set the similarity threshold between 0.5 and 0.99.",
        "返信の監視間隔は100〜30,000msで指定してください。": "Set the reply polling interval between 100 and 30,000 ms.",
        "本文更新が止まってから待つ時間は2〜60秒で指定してください。": "Set the wait after the last message update between 2 and 60 seconds.",
        "ソナー音量は0〜1で指定してください。": "Set the sonar volume between 0 and 1.",
        "返信の待ち時間は30〜900秒で指定してください。": "Set the reply timeout between 30 and 900 seconds.",
        "返信の待ち時間は、本文更新が止まってから待つ時間より長くしてください。": "The reply timeout must be longer than the wait after the last message update.",
        "テスト": "Test",
        "設定の形式を読み取れません。": "Could not read the settings format.",
        "\n話者類似度 %.3f（参考値・単独発話を拒否するしきい値ではありません）": "\nSpeaker similarity %.3f (informational; not a threshold for rejecting a single speaker)",
        "話者類似度 %.3f（しきい値 %.3f）": "Speaker similarity %.3f (threshold %.3f)",
        " / 発話全体 %.3f": " / Entire utterance %.3f",
        "%.2f秒: %.3f": "%.2f s: %.3f",
        "\n区間別: ": "\nSegments: ",
        "返信先のDMが変わりました。このDMで新しい返信を受け取ってから実行してください。": "The reply destination DM has changed. Receive a new reply in this DM before trying again.",
        "許可されていない通信先です。": "This network destination is not allowed.",
        "Webexからの応答を解釈できません。": "Could not interpret the Webex response.",
        "Webex URLが不正です。": "Invalid Webex URL.",
        "Webex IDが不正です。": "Invalid Webex ID.",
        "ページリンクの通信先が不正です。": "Invalid destination in the pagination link.",
        "Webex APIエラー（HTTP {0}）。権限と接続を確認してください。": "Webex API error (HTTP {0}). Check permissions and the connection.",
        "Webexのページリンクが不正です。": "Invalid Webex pagination link.",
        "DM検索のページ数が上限を超えました。条件を変更して再検索してください。": "DM search exceeded the page limit. Change the filter and search again.",
        "メッセージのページ数が上限を超えました。": "Message retrieval exceeded the page limit.",
        "送信本文は1〜7,000 UTF-8バイトで指定してください。": "The message must be between 1 and 7,000 UTF-8 bytes.",
        "スクリーンショットが10 MBを超えています。": "The screenshot exceeds 10 MB.",
        "言語": "Language",
        "言語を切り替えると、通常・返信用の合言葉と両方のテンプレートを初期値に戻します。変更を保存すると次回もこの言語を使います。": "Switching languages resets both wake phrases and both message templates to their defaults. Save Changes to keep this language for the next launch.",
        "記録なし": "No events",
        "テンプレートに {{transcript}} が必要です。": "The template must contain {{transcript}}.",
        "テンプレートの括弧が閉じていません。": "A template placeholder is not closed.",
        "screen条件は入れ子にできません。": "Screen conditions cannot be nested.",
        "screen条件の開始がありません。": "A screen condition has no opening marker.",
        "未対応のテンプレート変数です: {0}": "Unsupported template variable: {0}",
        "screen条件が閉じていません。": "A screen condition is not closed.",
        "送信する音声文字起こしが空です。": "The speech transcript to send is empty.",
        "メッセージが長すぎます（上限7,000 UTF-8バイト）。発話・OCR・テンプレートを短くしてください。送信はしていません。": "The message exceeds 7,000 UTF-8 bytes. Shorten the transcript, OCR, or template. Nothing was sent.",
        "録音は0.25〜60秒の有効な音声を使用してください。": "Use a valid audio recording between 0.25 and 60 seconds long.",
        "本人照合には指示の発話が短すぎます。合言葉から、指示をもう少し長く話してください（音声区間1.6秒以上）。": "The command is too short for speaker verification. Start with the wake phrase and speak a longer command (at least 1.6 seconds of speech).",
        "本人照合用に3秒以上の発話を含む音声を登録してください。": "Register reference audio with at least 3 seconds of speech for speaker verification.",
        "登録した話者と一致しない音声を除外しました。": "Audio that did not match the registered speaker was excluded.",
        "声の優先: 短い発話も受け付けます。合言葉と認識結果で判断します。": "Speaker preference: Short utterances are accepted, based on the wake phrase and recognition result.",
        "声の優先用に3秒以上の発話を含む参照音声を登録してください。": "Register reference audio with at least 3 seconds of speech for speaker preference.",
        "声の優先: 単独・区別が不確かな発話を受け付けました。": "Speaker preference: Accepted a single speaker or speech whose speakers could not be reliably distinguished.",
        "声の優先: 区別できた複数の声から、登録した声に近い発話を優先しました。": "Speaker preference: Favored speech closest to the registered voice among distinguishable speakers.",
        "音声区間が不足しています。": "Insufficient speech duration.",
        "認識の信頼度が不足しています。もう一度話してください。": "Recognition confidence is too low. Please speak again.",
        "声の再現用の参照音声は3〜30秒の有効な音声を使用してください。": "Use valid reference audio between 3 and 30 seconds long for voice cloning.",
        "音声再現には参照音声と一致する文字起こしが必要です。": "Voice cloning requires a transcript that matches the reference audio.",
        "参照音声のノイズ軽減設定が不正です。": "Invalid reference audio noise reduction setting.",
        "短い区間に分割しても音声を生成できませんでした。参照音声・参照本文を確認し、読み上げを試してください。返信全文はホームで確認できます。": "Speech generation failed even after splitting into shorter segments. Check the reference audio and transcript, then preview the voice. The full reply is on Home.",
        "音声生成結果が不正です。": "Invalid generated audio.",
        "読み上げ処理が開始されていません。": "Speech output has not started.",
        "読み上げ音声の保存先が不正です。": "Invalid destination for generated speech.",
        "読み上げ音声を生成できませんでした。": "Could not generate speech audio.",
        "Whisperモデルが未配置です。scripts/download-models.sh asr を実行してください。": "The Whisper model is missing. Run scripts/download-models.sh asr.",
        "音声再現モデルが未配置です。scripts/download-models.sh voice を実行してください。": "The voice cloning model is missing. Run scripts/download-models.sh voice.",
        "依存関係・モデル配置・ローカルVADを確認しました。音声認識の精度と声質は実際の録音で確認してください。": "Dependencies, model files, and local VAD checked. Test recognition accuracy and voice quality with actual recordings.",
        "未対応の音声処理です。": "Unsupported speech operation.",
        "リクエストが長すぎます。": "The request is too long.",
        "音声処理のリクエストが途中で終了しました。": "The speech processing request ended early.",
        "音声処理のリクエストはJSONオブジェクトで指定してください。": "The speech processing request must be a JSON object.",
        "ローカルモデルを実行できません。環境・モデルの配置を確認してください。": "Could not run the local model. Check the environment and model files.",
        "ローカルファイルが見つかりません。モデルと音声の設定を確認してください。": "Local file not found. Check the model and audio settings.",
        "読み上げ本文の単語を解析できません。": "Could not analyze word boundaries in the speech text.",
        "読み上げ本文は1〜20,000文字で指定してください。": "Speech text must contain between 1 and 20,000 characters.",
        "音声生成中にサンプルレートが変わりました。": "The sample rate changed during speech generation.",
        "参照音声の調整に失敗しました。参照録音を確認してください。": "Could not prepare the reference audio. Check the recording.",
        "参照音声のノイズ処理に失敗しました。参照録音を確認してください。": "Reference audio noise processing failed. Check the recording.",
        "見つかりません": "Not found",
    ]
}
